version: '3.1'

services:

    db:
        image: postgres:9.6
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
            POSTGRES_PASSWORD: dobjobs

    adminer:
        image: adminer
        ports:
            - 8080:8080
